stages:
  train:
    cmd: >
      poetry run python src/neuronal_activity/pretrain_vector_bert.py
      data/train_tensors.pt
      data/validation_tensors.pt
      models/trained_model_weights.pt
      train_config.yaml
    deps:
      - data/train_tensors.pt
      - data/validation_tensors.pt
      - config.yaml
    outs:
      - models/trained_model_weights.pt
    metrics:
      - lightning_logs/version_*/metrics.csv:
          cache: false
      - lightning_logs/version_*/hparams.yaml:
          cache: false
