"""Utility functions for the neuronal activity project."""

import random


def generate_codename() -> str:
    """Generate a random codename.

    Creates a codename by combining a random adjective and a random noun
    from predefined lists, separated by a hyphen.

    Returns:
        A string representing the generated codename.

    """
    adjectives: list[str] = [
        "adventurous",
        "bold",
        "brave",
        "bright",
        "calm",
        "charming",
        "cheerful",
        "daring",
        "delightful",
        "eager",
        "elegant",
        "energetic",
        "fancy",
        "faithful",
        "fearless",
        "generous",
        "gentle",
        "graceful",
        "happy",
        "honest",
        "humble",
        "inventive",
        "jolly",
        "joyful",
        "keen",
        "kind",
        "lively",
        "loyal",
        "loving",
        "merry",
        "modest",
        "motivated",
        "nice",
        "noble",
        "optimistic",
        "outgoing",
        "patient",
        "polite",
        "proud",
        "quick",
        "reliable",
        "respectful",
        "silly",
        "sincere",
        "spirited",
        "thoughtful",
        "trustworthy",
        "upbeat",
        "vibrant",
        "warm",
        "witty",
        "youthful",
        "zany",
        "zealous",
    ]
    nouns: list[str] = [
        "alligator",
        "anteater",
        "armadillo",
        "badger",
        "bat",
        "bear",
        "beaver",
        "buffalo",
        "camel",
        "cheetah",
        "chimpanzee",
        "chipmunk",
        "chinchilla",
        "crocodile",
        "dolphin",
        "eagle",
        "elephant",
        "falcon",
        "ferret",
        "flamingo",
        "fox",
        "gerbil",
        "giraffe",
        "gorilla",
        "guinea pig",
        "hamster",
        "hedgehog",
        "hippopotamus",
        "kangaroo",
        "koala",
        "lemur",
        "leopard",
        "lion",
        "lynx",
        "meerkat",
        "mole",
        "monkey",
        "mouse",
        "orangutan",
        "otter",
        "owl",
        "panda",
        "parrot",
        "peacock",
        "penguin",
        "porcupine",
        "rabbit",
        "raccoon",
        "rat",
        "rhinoceros",
        "shark",
        "skunk",
        "sloth",
        "sparrow",
        "squirrel",
        "swan",
        "tiger",
        "weasel",
        "whale",
        "wolf",
        "woodpecker",
        "zebra",
    ]

    adjective: str = random.choice(adjectives)  # noqa: S311 # nosec: B311
    noun: str = random.choice(nouns)  # noqa: S311 # nosec: B311

    return f"{adjective}-{noun}"
