name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
      statuses: write
    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup-env

    - name: Run tests
      run: make test-ci
      id: run-tests

    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1

    - name: Report LCOV
      uses: zgosalvez/github-actions-report-lcov@v4.1.16
      with:
        coverage-files: coverage.lcov
        minimum-coverage: 70
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        update-comment: true

    - name: Upload pytest results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: pytest.xml
      if: always()

    - name: Publish Test Results
      uses: ./.github/actions/publish-test-results
      if: always()
      with:
        test-results-file: pytest.xml
