name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup-env

    - name: Run tests
      run: make test-ci
      continue-on-error: true

    - name: Upload pytest results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: pytest.xml
      if: always()

    - name: Publish Test Results
      uses: ./.github/actions/publish-test-results
      if: always()
      with:
        test-results-file: pytest.xml
