name: Pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup-env

    - uses: pre-commit/action@v3.0.1
