name: Pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/actions/setup-env

    - name: Check Ruff installation and version
      run: |
        RUFF_PATH=$(poetry run which ruff)
        echo "Ruff path: $RUFF_PATH"
        RUFF_VERSION=$(poetry run ruff --version)
        echo "Ruff version: $RUFF_VERSION"
      shell: bash

    - uses: pre-commit/action@v3.0.1
